export const data = {
  products : [
    {
      _id:'1',
      name:'Azipluocueta',
      category:'singleFamily',
      image:'/Images/family (1).jpg',
      price:237,
      rating:3.9,
      numReviews:13,
      roomsFree:2,
      company:'Chelsea',
      description:'moderate home in a moderate quater fool of joy',
    },
    
    
      {
    _id:'4',
    name:'David',
    category:'multiFamily',
    image:'/Images/family (4).jpg',
    price:186,
    rating:3.0,
    numReviews:63,
    roomsFree:234,
    company:'PSG',
    description:'moderate home in a moderate quater fool of joy',
  },

    {
    _id:'9',
    name:'Icardi',
    category:'mFamilultiy',
    image:'/Images/family (9).jpg',
    price:602,
    rating:4.2,
    roomsFree:0,
    numReviews:1214,
    company:'Internazional',
    description:'moderate home in a moderate quater fool of joy',
  },
  {
  _id:'2',
  name:'Ballack',
  category:'multiFamily',
  image:'/Images/family (2).jpg',
  price:345,
  rating:4.1,
  numReviews:13,
  roomsFree:7,
  company:'Chelsea',
  description:'moderate home in a moderate quater fool of joy',
},
  {
      _id:'10',
      name:'NeyMar',
      category:'room',
      image:'/Images/room (1).jpg',
      price:34,
      rating:4.6,
      roomsFree:12,
      company:'Santos',
      numReviews:297,
      description:'apartment open to students ',
    },

    {
    _id:'7',
    name:'Pique',
    category:'singleFamily',
    image:'/Images/family (7).jpg',
    price:73,
    rating:3.6,
    roomsFree:0,
    company:'Barcelona',
    numReviews:13,
    description:'moderate home in a moderate quater fool of joy',
  },
  {
    _id:'8',
    name:'Haaland',
    category:'multiFamily',
    image:'/Images/family (8).jpg',
    price:147,
    rating:4.3,
    roomsFree:93,
    numReviews:333,
    company:'Dortumund',
    description:'moderate home in a moderate quater fool of joy',
  },

    {
      _id:'11',
      name:'Messi',
      category:'room',
      image:'/Images/room (2).jpg',
      price:6784343,
      rating:4.9999999999999999,
      numReviews:20004325,
      roomsFree:3,
      company:'Barcelona',
      description:'Luxiruios appartment  ',
    },
    {
      _id:'12',
      name:'Kaka',
      category:'room',
      image:'/Images/room (3).jpg',
      price:2007,
      rating:4.1,
      numReviews:125,
      company:'Ac Milan',
      roomsFree:231,
      description:'apartment open to students ',
    },
        {
      _id:'3',
      name:'Christiano',
      category:'singleFamily',
      image:'/Images/family (3).jpg',
      price:237,
      rating:4.4,
      numReviews:17,
      roomsFree:28,
      company:'Real Madrid',
      description:'moderate home in a moderate quater fool of joy',
    },
    {
      _id:'13',
      name:'Suarez',
      category:'room',
      image:'/Images/room (4).jpg',
      price:167,
      rating:4.2,
      numReviews:25,
      roomsFree:9,
      company:'Liverpool',
      description:'apartment open to students ',
    },
      {
    _id:'5',
    name:"Eto'o",
    category:'singleFamily',
    image:'/Images/family (5).jpg',
    price:267,
    rating:3.9,
    roomsFree:25,
    company:'Mankashkanla',
    numReviews:13,
    description:'moderate home in a moderate quater fool of joy',
  },
  {
    _id:'6',
    name:'Fernando',
    category:'singleFamily',
    image:'/Images/family (6).jpg',
    price:89,
    rating:2.4,
    company:'Atletico Madrid',
    roomsFree:8,
    numReviews:5,
    description:'moderate home in a moderate quater fool of joy',
  },
    
    {
    _id:'14',
    name:'Maradona',
    category:'room',
    image:'/Images/room (7).jpg',
    price:345,
    rating:4.1,
    numReviews:13,
    roomsFree:0,
    company:'Chelsea',
    description:'moderate home in a moderate quater fool of joy',
  },
  {
    _id:'15',
    name:'Foe',
    category:'flat',
    image:'/Images/flat (6).jpg',
    price:237,
    rating:4.4,
    numReviews:17,
    roomsFree:100,
    company:'Real Madrid',
    description:'moderate home in a moderate quater fool of joy',
  },
  ]
}