export {default as Header} from './header/Header'
export {default as Price} from './Price/Price'
export {default as Thumbnails} from './Thumbnails/Thumnails'
export {default as StarRating} from './StarRating/StarRating'
export {default as Search} from './Search/Search'
export {default as Tags} from './Tags/Tags'
export {default as Title} from './Title/Title'
export {default as NotFound} from './NotFound/NotFound'